### ISSUE TITLE
"Media created" property not being recognized as possible create date

### ISSUE THREAD

**Issue by wicked-head** [TheLastGimbus/GooglePhotosTakeoutHelper#196] opened 2023-04-11 01:39 UTC
Hi,

Some files got "rejected" because the program could not calculate the date, but looking into the file properties there is a property named "Media created" which represents the create date time of the file.

![image](https://user-images.githubusercontent.com/130382585/231033028-b35ee2b2-b792-43c1-87f0-ebd2d01dbf93.png)

Is is possible to include that as part of the logic?

Thanks once again

**Comment by wicked-head** [comment] 2023-04-11 09:47
Hi,

Yes its a video. and it is the same example as the file i've uploaded in issue [197](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues/197).

I have not modified or change the file after the download from Google Photos and the .MOV file does not have any JSON.

If we duplicated the JSON from the .JPG for the .MOV would that theoretically work?

Thanks!

**Comment by TheLastGimbus** [comment] 2023-04-11 10:11
> If we duplicated the JSON from the .JPG for the .MOV would that theoretically work?

yes, i think we can add this to json-matching-algorithm soon :eyes:

for now, duplicate of #180

**Closed by TheLastGimbus** 2023-04-11 10:11 UTC
