### ISSUE TITLE
Couldn't find dates for a lot of MP4 files

### ISSUE THREAD

**Issue by Leonardo-Fiori** [TheLastGimbus/GooglePhotosTakeoutHelper#250] opened 2023-09-30 14:14 UTC
I have json files for everything, downloaded from Google Takeout. Most of the json metadata have been succesfully merged, but more than 4000 mp4 files have been left without a date, even if there was a proper json file to be used!

Here is an example: https://imgur.com/a/I1hgELY

That json refers to the HEIC version of that MP4 file. Why is it in MP4 tho? Should be in HEIC. Could this be the reason why it didn't find the date for it?

**Comment by TheLastGimbus** [comment] 2023-09-30 19:50
Well well, you report that right in the middle of hot discussion just about that - check everything out at #180 

closing this as a duplicate of said issue, feel invited to disucss there if you have any ideas - for now, you can try the nightly mentioned somewhere there/in the PR

**Closed by TheLastGimbus** 2023-09-30 19:50 UTC
