### ISSUE TITLE
Apple iOS Live Photo associated video files result in date unknown due to duplicate naming

### ISSUE THREAD

**Issue by zjyin-umich** [TheLastGimbus/GooglePhotosTakeoutHelper#295] opened 2024-03-10 05:20 UTC
Preliminary Information:
Hello, its my first time opening an issue ticket, Ill try to be as specific as possible. 

GPTH used: Windows executable
Setup: Photos taken from enterprise google takeout, GPTH to fix dates, transfer all files to homeserver for reupload on different account via android
Notes: Most photos take from an iphone, some photos from DSLR

Apple iOS's way of managing live photos results in a two part system, a single image in jpg/JPG/JPEG/HEIC format and a single video file in MP4/MOV format(In my run theyre JPG/MP4 but i think these depends on photo quality settings in the phone when the photo was originally taken). The associated JSON file is only tied to the image. There is no associated JSON file for the associated video file.

When running these files through GPTH, all images for live photos are corrected correctly. However, all video files associated with the live photo result in date unknown. 
`Guessing dates from files : ██...................................... 593/10422
Can't get date on C:\Users\USERNAME\Pictures\ALBUMNAME\takeout-20240901T134978Z-001\Takeout\Google Photos\Photos from 2020\IMG_3641.MP4`

`Can't get date on C:\Users\USERNAME\Pictures\ALBUMNAME\takeout-20240901T134978Z-001\Takeout\Google Photos\Photos from 2023\lp_image(10).MP4
Guessing dates from files : █████████████████████████████........... 7760/10422`

With the way most cameras, including the iphone, go about with naming convention, there could be potentially multiple files with the same name(ex: IMG_3641) and slightly different extensions(.jpg vs .JPG) which makes this a bit confusion to the eye. 
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/47654549/d76d4c2f-4bc5-429a-ba36-1b4ca6304ae3)

(Note: IMG_1444.jpg is a different photo and _**NOT**_ associated with IMG_1444.JPG/IMG_1444.MP4. 
IMG_1444.JPG is the photo associated with IMG_1444.MP4)
![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/47654549/81db7eee-4ee4-428c-8005-c920efc70f03)

Perhaps its possible to take the .MP4 name and using it to search for the assoiated JPG name/json, or maybe theres a way to do it with the .assocFile name extension? Im not quite clear on how to solve this but i figured id drop what ive observed incase anyone else runs into this issue :)

**Comment by Randomblock1** [comment] 2024-03-12 13:40
Probably a duplicate of #180.
Anyway here's a Python script that will match JSON to both files: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues/180#issuecomment-1872560165

**Comment by TheLastGimbus** [comment] 2024-03-19 20:24
Thanks @Randomblock1 <3

**Closed by TheLastGimbus** 2024-03-19 20:24 UTC
