### ISSUE TITLE
cannot move file to a different disk drive

### ISSUE THREAD

**Issue by jhennig** [TheLastGimbus/GooglePhotosTakeoutHelper#284] opened 2024-02-06 18:45 UTC
Hi,
When using windoza 3.4.3 I get the following error

 Unhandled exception:
FileSystemException: Cannot rename file to 'E:\GooglePhotosCleaned\ALL_PHOTOS\1906\07\36913273772_d934833874_h.jpg', path = 'F:\Google\Takeout\Google Photos\Photos from 1906\36913273772_d934833874_h.jpg' (OS Error: The system cannot move the file to a different disk drive.
, errno = 17)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.rename.<anonymous closure> (dart:io/file_impl.dart:335)
<asynchronous suspension>
#2      moveFiles.moveFile (package:gpth/moving.dart:135)
<asynchronous suspension>
#3      moveFiles (package:gpth/moving.dart:140)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///d:/a/googlephotostakeouthelper/googlephotostakeouthelper/bin/gpth.dart:373)
<asynchronous suspension>

**Comment by TheLastGimbus** [comment] 2024-02-06 19:19
Yep, that's not working now, but you don't have to do this: https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues/251#issuecomment-1747006340

closing as duplicate of #251

**Closed by TheLastGimbus** 2024-02-06 19:19 UTC
