### ISSUE TITLE
OS Error: The system cannot move the file to a different disk drive

### ISSUE THREAD

**Issue by stantaneous** [TheLastGimbus/GooglePhotosTakeoutHelper#326] opened 2024-07-07 16:10 UTC
I am facing this error with the version [v3.4.3](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/releases/tag/v3.4.3).

For my input folder, I am choosing the folder from D: drive and for the output folder, I am choosing the folder on C: drive. Looks like the script is not able to move the files from D: drive to C: drive. 

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/24977958/e5ce721a-3fe6-44c2-963e-824507af6e71)

I guess I can fix this by choosing the folder from same drive. However, it would be better to have a fix for this error. It might be helpful to choose to different drive for output in case the input drive does not have space available.

**Comment by palijn** [comment] 2024-07-07 18:51
I am not sure this is really adviseable. It's nice that gpth is extremely fast and robust because it moves the file within the same filesystem, which actually doesn't move any data. 
Moving across filesystems always is a copy followed by a delete : much slower and prone to errors.

**Comment by stantaneous** [comment] 2024-07-08 04:35
I can understand that it is not advisable, it would be better to not allow the user to choose the output folder from different file system or show the error messages. I could only see the error message when i ran the application though terminal. It just crashed if we run it interactively without showing any errors.

**Comment by TheLastGimbus** [comment] 2024-08-08 12:09
duplicate of #251 

> it would be better to not allow the user

yeah that's something to consider, thanks!

**Closed by TheLastGimbus** 2024-08-08 12:09 UTC
