### ISSUE TITLE
Live Photos / HEICs

### ISSUE THREAD

**Issue by aidan-gibson** [TheLastGimbus/GooglePhotosTakeoutHelper#225] opened 2023-07-17 15:32 UTC
When a HEIC with "Live Photo" is enabled, Google Photos splits the HEIC file into a still, which still has the extension HEIC, and an MP4 with the same name. This program classifies the MP4 as metadata unknown, when it should match the HEIC (or, even better, should remerge the HEIC and MP4 into one HEIC, although I couldn't find any tools to do so). 

Fortunately, if importing into Apple Photos, the Photos app understands putting them back together for the most part, so turned out to be a non-issue for me. 

(Thank you for making this fantastic script!)

**Comment by BobTheSoftwareDeveloper** [comment] 2023-07-21 11:00
#224 I recently made a PR for iOS Live Photo support

**Comment by TheLastGimbus** [comment] 2023-08-11 00:14
Duplicate of #180

I will look into pr in some time :eyes:

**Closed by TheLastGimbus** 2023-08-11 00:14 UTC
