### ISSUE TITLE
Geo and Tima data

### ISSUE THREAD

**Issue by Anas-Sherif** [TheLastGimbus/GooglePhotosTakeoutHelper#201] opened 2023-04-29 20:04 UTC
Is there a way to add geodata? I can't use the other version since the releases are windows only.

**Comment by TheLastGimbus** [comment] 2023-05-03 09:16
Hi! Currently, no, because gpth doesn't re-insert the exifs. However, you photos should have everything as original, since google doesn't seem to strip it. See disctussion #191 

for now, closing this issue as duplicate of #195

**Closed by TheLastGimbus** 2023-05-03 09:16 UTC
