### ISSUE TITLE
Strategies for timestamping more photos and videos.

### ISSUE THREAD

**Issue by giantpune** [TheLastGimbus/GooglePhotosTakeoutHelper#102] opened 2021-11-04 16:43 UTC
After running this project, I had a number of leftover files with dates equal to the date of my google takeout.zip.  

Many of the files had timestamps available in the filename in a predictable format.
Other files matched closely with a different file which we did have a timestamp in the json file that was already able to be pulled out.

Here's the code I used and it cleaned up most of the remaining ~300 files that `google-photos-takeout-helper` was not able to figure out the timestamps for.  
 - check for timestamps for files with similar names, but without the `(1)` and `-edited` in their name.  Or in a similarly named jpg file.  For the android motion videos, there's a jpg and mp4 with identical names, so we can use the timestamp from the jpg on the mp4.
 - check for timestamps in the filename itself

```python
import datetime
import os

folder = 'processed'

fnames = []
for (dirpath, dirnames, filenames) in os.walk(folder):
  fnames.extend(filenames)
  break 
for name in fnames:
  base = os.path.splitext(name)[0]
  base = base.rstrip("(1)") \
             .rstrip("(2)") \
             .rstrip("_1") \
             .rstrip("_a") \
             .rstrip("_b") \
             .rstrip("-edited")
  
  base += '.jpg'
  
  stinfo = os.stat(folder + '/' + name)
  
  # these are earlier than my google takeout zip.  so already modified.  no need to look at them again
  if stinfo.st_mtime < 1635785952:
    continue
  
  if base == name:
    continue
  
  if not os.path.exists(folder + '/' + base):
    # nothing to copy from
    print(f'need to figure out {name}')
    if "_20" in name:
      print(f'timestame in name?')
      ts = os.path.splitext(name)[0] \
           .rstrip("(1)")
      ts = "20" + ts.split("_20", 1)[1]
      print(f"datestring: {ts}")
      
      try:
       date = datetime.datetime.strptime(ts, "%Y%m%d_%H%M%S")
       print(f'parsed as date!: {date}')
       os.utime(folder + '/' + name,(date.timestamp(),date.timestamp()))
      except:
        pass
    continue

  print(f'copying attributes from sister jpg file: {base} -> {name}')
  stinfo = os.stat(folder + '/' + base)
  os.utime(folder + '/' + name,(stinfo.st_atime, stinfo.st_mtime))
```

**Comment by TheLastGimbus** [comment] 2021-11-19 18:15
Huh, I could potentially make some additional utils that would be unsafe but get things like this done...

**Comment by blakethepatton** [comment] 2021-12-03 04:02
Google photos has an api... I wonder if it'd be practical to pull data from the api. I have too many to count videos/images that dates couldn't have their exif data populated. I may just try it out. 

Thanks @TheLastGimbus for making this project btw!

**Comment by TheLastGimbus** [comment] 2021-12-04 16:15
People where mildly satisfied with the api... it can't pull original quality photos / do some other stuff... but you can try it out, maybe even share here how it went :+1:

**Comment by TheLastGimbus** [comment] 2022-12-17 23:31
Those code suggestions are pretty good... i'll "merge" this issue (mark it as duplicate) for use later

duplicate of #92

**Closed by TheLastGimbus** 2022-12-17 23:31 UTC
